# Generated by Django 5.2 on 2025-07-09 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
