# Generated by Django 5.2 on 2025-07-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_transaction_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=9999999999, max_length=10),
        ),
    ]
